# Generated by Selenium IDE
import asyncio
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUntitled():
    def setup_method(self):
        options = webdriver.ChromeOptions()
        self.vars = {}
        options.add_argument("start-maximized")
        options.add_argument("disable-infobars")  # disabling infobars
        options.add_argument("--disable-extensions")  # disabling extensions
        options.add_argument("--no-sandbox")
        # overcome limited resource problems
        options.add_argument("--disable-dev-shm-usage")

        self.driver = webdriver.Chrome('mac/chromedriver', options=options)
        #

    def teardown_method(self):
        self.driver.quit()

    def test_untitled(self):
        self.driver.get(
            "https://dash.cloudflare.com/03b13226b9ea04db1bafaeb03987d0ec/images/images")
        self.driver.set_window_size(1182, 859)
        time.sleep(2)
        self.driver.find_element(By.NAME, "toggleAll").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c_ss").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c_ss > span").click()
        time.sleep(2)
        self.driver.find_element(By.NAME, "toggleAll").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c_ss").click()
        self.driver.find_element(By.CSS_SELECTOR, ".c_ss > span").click()


crawler = TestUntitled()
crawler.setup_method()
loop = asyncio.get_event_loop()
loop.run_until_complete(crawler.test_untitled())
crawler.teardown_method("")
