# Generated by Selenium IDE
from math import fabs

import os
import asyncio
from sched import scheduler
import time
from xml.etree.ElementInclude import include
from bs4 import BeautifulSoup

import requests
import json
from dotenv import load_dotenv
from email.mime import image
from requests_toolbelt import MultipartEncoder
from datetime import datetime, timedelta
from prisma import Prisma
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from re import sub
from decimal import Decimal
import shutil
from urllib import request
import time
import re
from tomlkit import item, string
import schedule
import logging
import logging.handlers

import binascii

# LOG UPDATE ITEM
log_update = logging.getLogger('snowdeer_log')
log_update.setLevel(logging.DEBUG)

formatter = logging.Formatter(
    '[%(asctime)s] [%(levelname)s] (%(filename)s:%(lineno)d) > %(message)s')

fileHandler = logging.FileHandler('./log/log.txt', encoding='utf-8')
streamHandler = logging.StreamHandler()

fileHandler.setFormatter(formatter)
streamHandler.setFormatter(formatter)

log_update.addHandler(fileHandler)
log_update.addHandler(streamHandler)


class GetAuctionInfo():
    API_HOST = 'https://api.cloudflare.com'

    data = {}

    def setup_method(self, method):
        # 옵션 생성
        options = webdriver.ChromeOptions()
        #options = webdriver.FirefoxOptions()

        options.add_argument("--headless")
        # open Browser in maximized mode
        options.add_argument("start-maximized")
        options.add_argument("disable-infobars")  # disabling infobars
        options.add_argument("--disable-extensions")  # disabling extensions
        options.add_argument("--no-sandbox")
        # overcome limited resource problems
        options.add_argument("--disable-dev-shm-usage")

        self.driver = webdriver.Chrome('linux/chromedriver', options=options)
        # self.driver = webdriver.Firefox(
        #     executable_path='linux/geckodriver', options=options)

        self.driver.implicitly_wait(3)

        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def req(self, path, query, method, data={}, field_data={}):
        url = self.API_HOST + path
        header = {
            'Authorization': os.environ.get('APP_KEY'),
            'Content-Type':  'application/json'
        }
        try:
            if method == 'GET':
                response = requests.get(url, headers=header)
            elif method == 'POST':
                response = requests.post(
                    url, headers=header, data=data)
                if response.status_code == 200:
                    return response.json()['result']

        except Exception as ex:
            print("Req exception : ", ex)
            return -1

    async def insertImage(self, imageObjects):
        db = Prisma()
        await db.connect()
        await db.image.create_many(
            data=imageObjects
        )
        print("Completed insert images")
        await db.disconnect()

    async def 기일내역_DB_업데이트(self, resultAuctionObjects, itemId):
        db = Prisma()
        await db.connect()

        await db.resultauction.delete_many(
            where={
                'itemId': itemId
            }
        )
        await db.resultauction.create_many(
            data=resultAuctionObjects
        )
        print("Completed insert result of auction")
        await db.disconnect()

    async def 경매상태_DB_업데이트(self, itemId, statusOfItem, status):

        db = Prisma()
        await db.connect()

        if statusOfItem == '':
            await db.item.update(
                where={
                    'id': itemId
                },
                data={
                    'status': status,
                }
            )
        else:
            await db.item.update(
                where={
                    'id': itemId
                },
                data={
                    'status': status,
                    'lastestStatus':  statusOfItem
                }
            )
        await db.disconnect()

    async def insertEstateList(self, estateList):
        db = Prisma()
        await db.connect()

        await db.realestatelist.create_many(
            data=estateList
        )
        print("Completed insert estateLists")
        await db.disconnect()

    async def insertLeaseDetail(self, leaseDetails):
        db = Prisma()
        await db.connect()

        await db.leasedetail.create_many(
            data=leaseDetails
        )
        print("Completed insert leaseDetails")
        await db.disconnect()

    async def insertLeasePeople(self, leasePeoples):

        db = Prisma()
        await db.connect()

        await db.leasepeople.create_many(
            data=leasePeoples
        )
        print("Completed insert lease peoples")
        await db.disconnect()

    async def selectItem(self, caseNumber):
        db = Prisma()
        await db.connect()

        items = await db.item.find_many(
            where={
                'caseNumber': caseNumber,
            }
        )
        await db.disconnect()

        return len(items)

    async def selectItemByCaseIndex(self, caseIndex, itemNumber):
        db = Prisma()
        await db.connect()
        items = await db.item.count(
            where={
                'caseIndex': caseIndex,
                'itemNumber': itemNumber
            }
        )
        await db.disconnect()

        if items == 0:
            return True
        else:
            return False

    async def checkImageDuplicated(self, caseNumber):
        db = Prisma()
        await db.connect()

        images = await db.image.count(
            where={
                'caseNumber': caseNumber
            }
        )
        await db.disconnect()

        if images == 0:
            return False
        else:
            return True

    async def insertItemInfo(self, caseIndex, court, status):
        db = Prisma()
        await db.connect()
        print(caseIndex, " ", court, " ", status)
        item = await db.item.create(
            data={
                'caseIndex': caseIndex,
                'court': court,
                'status': status
            }
        )
        await db.disconnect()
        return item.id

    async def insertItem(self, caseNumber, caseIndex, itemNumber, itemType, initialPrice, minPrice, bidType, saleDate,
                         description, itemLocation, court, caseApplyDate, auctionApplyDate, allocationApplyDate,
                         requestPrice, appraisal, areaOfBuilding, areaOfGround, numOfPass, share, pdfValuation):
        db = Prisma()
        await db.connect()
        item = await db.item.create(
            data={
                'caseNumber': caseNumber,
                'caseIndex': caseIndex,
                'itemNumber': itemNumber,
                'itemType': itemType,
                'initialPrice': initialPrice,
                'minPrice': minPrice,
                'bidType': bidType,
                'saleDate': saleDate,
                'description': description,
                'itemLocation': itemLocation,
                'court': court,
                'caseApplyDate': caseApplyDate,
                'auctionApplyDate': auctionApplyDate,
                'allocationApplyDate': allocationApplyDate,
                'requestPrice': requestPrice,
                'appraisal': appraisal,
                'areaOfBuilding':     areaOfBuilding,
                'areaOfGround': areaOfGround,
                'numOfPass':  numOfPass,
                'share': share,
                'pdfValuation': pdfValuation
            }
        )
        print("Created : ", caseNumber)
        await db.disconnect()

        return item.id

    async def deleteAll(self):
        db = Prisma()
        await db.connect()
        await db.item.delete_many({})
        await db.image.delete_many({})
        await db.disconnect()

    def cloudFlareUpload(self, imgFileName, imageObjects, caseNumber):

        while True:
            print("cloudFlareUpload : ", imgFileName)
            try:
                uploadURL = None
                done = False
                while True:
                    try:
                        header = {
                            'Authorization': os.environ.get('APP_KEY'),
                            'Content-Type':  'application/json',
                            # Github runner
                            # "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5288.0 Safari/537.36"
                            # Localf
                            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"

                        }
                        responseGetUploadUrl = requests.post(self.API_HOST + '/client/v4/accounts/{}/images/v1/direct_upload'.format(
                            os.environ.get('CF_ACCOUNT_ID')), headers=header, data={})

                        if responseGetUploadUrl is not None:
                            responseGetUploadUrl = responseGetUploadUrl.json()
                            if responseGetUploadUrl['success'] == True:
                                uploadURL = responseGetUploadUrl['result']['uploadURL']
                                print(
                                    "Get uploadUrl : ", uploadURL)
                                break
                            else:
                                time.sleep(1)
                        else:
                            time.sleep(1)
                    except Exception as uploadUrlException:
                        print("uploadUrlException : ",
                              uploadUrlException)

                while True:
                    try:
                        files = {'file': open(imgFileName, 'rb')}
                        if uploadURL is not None:
                            responseUpload = requests.post(
                                uploadURL, files=files, data={})
                            if responseUpload is not None:
                                responseUpload = responseUpload.json()
                                if responseUpload['success'] == True:
                                    imageObjects.append(
                                        {"caseNumber": caseNumber, "cloudflareImgId": responseUpload['result']['id']})
                                    done = True
                                    print("Completed upload : ",
                                          imgFileName)
                                    break
                                else:
                                    print(responseUpload)
                                    break
                            else:
                                break
                        else:
                            break
                    except Exception as uploadUrlError:
                        print("Error uploadUrl : ",
                              uploadUrlError)
                        time.sleep(1)
                        continue
                if done == True:
                    break

            except Exception as CloudFlareError:
                print("CloudFlareError : ", CloudFlareError)
                continue

    async def 법원경매정보_물건리스트_가져오기(self):
        itemList = []
        isFirst = True

        table = self.driver.find_elements(
            By.XPATH, "//*[@id='contents']/div[4]/form[1]/table")

        for line in table:
            chks = line.find_elements(By.NAME, "chk")

            for chk in chks:
                inputValue = chk.get_attribute("value").split(',')
                if isFirst == True:
                    firstItem = (inputValue[1], inputValue[2])
                    isFirst = False

                # Duplicated check
                duplicated = await self.selectItemByCaseIndex(inputValue[1], inputValue[2])

                if duplicated == False:
                    print("PASS : ", inputValue[1], " ", inputValue[2])

                    # 감정평가서 업데이트
                    if firstItem == (inputValue[1], inputValue[2]):
                        itemList.append(
                            (inputValue[1], inputValue[2], True))
                    else:
                        itemList.append(
                            (inputValue[1], inputValue[2], False))

                else:
                    print("ADD : ", inputValue[1], " ", inputValue[2])

                    # 전체 업데이트
                    if firstItem == (inputValue[1], inputValue[2]):
                        itemList.append(
                            (inputValue[1], inputValue[2], True))
                    else:
                        itemList.append(
                            (inputValue[1], inputValue[2], False))

        return itemList

    async def 현황조사서_데이터(self, itemId, itemNumber):
        log_update.debug("현황조사서 시작")

        try:
            leaseDetails = []
            leasePeoples = []

            self.vars["window_handles"] = self.driver.window_handles
            self.driver.find_element(
                By.XPATH, "//img[@alt='현황조사서 팝업']").click()

            self.vars["win7232"] = self.wait_for_window(2000)
            self.vars["root"] = self.driver.current_window_handle

            self.driver.switch_to.window(self.vars["win7232"])

            html = self.driver.page_source
            soup = BeautifulSoup(html, 'html.parser')
            contents = soup.find(id='pop_contents_1')

            부동산의_점유관계_Tables = contents.find_all(
                'table', {"summary": "부동산의 점유관계 표"})

            for 부동산의_점유관계 in 부동산의_점유관계_Tables:

                for tr in 부동산의_점유관계.find_all('tr'):
                    td = tr.find_all('td')
                    # if "소재지" in tr.text:
                    #     itemIndx = td[0].text.split('.')[0]
                    if "기타" in tr.text:
                        leaseDetails.append({"content": td[0].text.strip()})

            임대차_관계_조사서_Tables = contents.find_all(
                'table', {"summary": "임차 목적물의 용도 및 임대차 계약등의 내용 표 "})

            # leaseFlag = False
            # endFlag = False

            for 임대차 in 임대차_관계_조사서_Tables:
                점유인 = ""
                당사자구분 = ""
                점유부분 = ""
                점유기간 = ""
                보증금 = ""
                차임 = ""
                전입일자 = ""
                확정일자 = ""

                for tr in 임대차.find_all('tr'):
                    td = tr.find_all('td')
                    if "점유인" in tr.text:
                        점유인 = td[1].text.strip()
                        당사자구분 = td[2].text.strip()

                    if "점유부분" in tr.text:
                        점유부분 = td[0].text.strip()

                    if "점유기간" in tr.text:
                        점유기간 = td[0].text.strip()

                    if "보증(전세)금" in tr.text:
                        보증금 = td[0].text.strip()
                        차임 = td[1].text.strip()

                    if "전입일자" in tr.text:
                        전입일자 = td[0].text.strip()
                        확정일자 = td[1].text.strip()

                        leasePeoples.append({"leaseName": 점유인, "leaseType": 당사자구분,
                                             'deposit': 보증금, 'transferDate': 전입일자, 'confirmDate': 확정일자,
                                             'occupancy': 점유부분, 'period': 점유기간, 'rent': 차임})
            if len(leaseDetails) > 0:
                for leaseDetailItem in leaseDetails:
                    leaseDetailItem['itemId'] = itemId
                await self.insertLeaseDetail(leaseDetails)
                log_update.debug("임차내용 DB Insert 완료")

            if len(leasePeoples) > 0:
                for leasePeopleItem in leasePeoples:
                    leasePeopleItem['itemId'] = itemId
                await self.insertLeasePeople(leasePeoples)
                log_update.debug("임차인 DB Insert 완료")

        except Exception as Error_현황조사서:
            log_update.error("Error_현황조사서")
            log_update.error(Error_현황조사서)

        finally:
            self.driver.close()
            self.driver.switch_to.window(self.vars["root"])
            self.driver.switch_to.frame(0)

    async def 목록내역_데이터(self, itemId):
        log_update.debug("목록내역 시작")
        estateListTable = self.driver.find_element(
            By.XPATH, "//*[@id='contents']/div[6]/table")

        estateListTbody = estateListTable.find_element(
            By.TAG_NAME, "tbody")

        areaOfGround = 0
        areaOfBuilding = 0
        estateList = []

        estateIdx = 0

        for tr in estateListTbody.find_elements(By.TAG_NAME, "tr"):

            tds = tr.find_elements(By.TAG_NAME, "td")

            estateLocation = self.driver.find_element(
                By.XPATH,
                "//*[@id='contents']/div[4]/table[1]/tbody/tr[" + str(5 + estateIdx) + "]/td").text.strip()

            estateUsage = ""

            if estateLocation[0] == "(":
                for usageChar in estateLocation:
                    if usageChar == ")":
                        estateUsage += usageChar
                        estateLocation = estateLocation.replace(
                            estateUsage, "").strip()
                        estateUsage = estateUsage.replace(
                            "(", "").replace(")", "").strip()

                        break
                    else:
                        estateUsage += usageChar
            else:
                estateUsage = "기타"

            if estateIdx == 0:
                itemLocation = estateLocation

            estateList.append({
                "num": int(tds[0].text),
                "type": tds[1].text,
                'detail': tds[2].text,
                "usage": estateUsage,
                "location": estateLocation}, )

            detailOfList = tds[2].text

            if tds[1].text == "토지":
                thisGround = float(0)
                for line in detailOfList.split("\n"):
                    if (line.startswith("주차장") or line.startswith("대") or line.startswith("임야") or line.startswith("구거") or line.startswith("잡종지") or line.startswith("묘지") or line.startswith("도로") or line.startswith("공장용지") or line.startswith("답") or line.startswith("하천") or line.startswith("전")) and line.endswith("㎡"):
                        thisGround = float(re.findall(
                            r'(\d+(?:\.\d+)?)', line)[0])

                    # 지분
                    if "매각지분" in line and "분의" in line:
                        isShare = float(0)
                        if len(re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)) > 0:
                            for each in re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line):
                                isShare += float(each[1]) / \
                                    float(each[0])

                            if isShare < 1.0:
                                share = True
                                thisGround = thisGround * isShare
                areaOfGround += thisGround

            elif tds[1].text == "집합건물":
                thisBuilding = float(0)
                thisGround = float(0)
                thisGroundArray = []
                groundShareIdx = 0

                for line in detailOfList.split("\n"):
                    line = line.strip()
                    # 건물
                    if "구          조" in line and "㎡" in line:
                        thisBuilding += float(
                            re.findall(r'(\d+(?:\.\d+)?)', line)[0])

                    if "면          적" in line and "㎡" in line:
                        thisBuilding += float(
                            re.findall(r'(\d+(?:\.\d+)?)', line)[0])

                    # 토지
                    # 면적
                    if (line.startswith("학교용지") or line.startswith("주차장") or line.startswith("대") or line.startswith("임야") or line.startswith("구거") or line.startswith("잡종지") or line.startswith("묘지") or line.startswith("도로") or line.startswith("공장용지") or line.startswith("답") or line.startswith("하천") or line.startswith("전")) and (line.endswith("㎡") or line.endswith("평방미터")):
                        thisGroundArray.append(
                            float(re.findall(r'(\d+(?:\.\d+)?)', line)[0]))

                    # 비율
                    if "." in line and "분의" in line and "매각지분" not in line:
                        line = line.replace(",", "")
                        if len(re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)) > 0:
                            numerator = float(re.findall(
                                r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)[0][0])
                            denominator = float(re.findall(
                                r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)[0][1])

                            if len(thisGroundArray) == 0:
                                if thisGround == 0:
                                    thisGround += denominator
                            else:
                                thisGroundArray[groundShareIdx] = thisGroundArray[groundShareIdx] * float(
                                    denominator / numerator)
                                thisGround += thisGroundArray[groundShareIdx]
                                groundShareIdx = groundShareIdx + 1
                    # 지분
                    if "매각지분" in line and "분의" in line:
                        isShare = float(0)
                        for each in re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line):

                            isShare += float(each[1]) / \
                                float(each[0])

                        if isShare < 1.0:
                            share = True
                            thisBuilding = thisBuilding * isShare
                            thisGround = thisGround * isShare

                areaOfBuilding += thisBuilding
                areaOfGround += thisGround

            elif tds[1].text == "건물":
                print("건물")

            estateIdx = estateIdx + 1

    async def 기일내역_데이터(self, itemId):
        formatYYYMMDD_HHMM = '%Y.%m.%d (%H:%M)'
        # 기일내역
        arrayResultAuction = []
        numOfPass = 0
        DetailOfSaleDate = self.driver.find_element(
            By.XPATH, "//*[@id='contents']/div[5]/table")

        tbody = DetailOfSaleDate.find_element(
            By.TAG_NAME, "tbody")
        for tr in tbody.find_elements(By.TAG_NAME, "tr"):
            tds = tr.find_elements(By.TAG_NAME, "td")

            saleDateRow = datetime.strptime(
                tds[0].get_attribute("innerText").strip(), formatYYYMMDD_HHMM)

            saleTypeRow = tds[1].get_attribute("innerText")
            saleLocationRow = tds[2].get_attribute("innerText")
            salePriceRow = tds[3].get_attribute("innerText")
            saleResultRow = tds[4].get_attribute("innerText")
            if "유찰" in saleResultRow:
                numOfPass += 1

            arrayResultAuction.append(
                {"date": saleDateRow, "type": saleTypeRow, 'location': saleLocationRow, 'minSalePrice': salePriceRow, 'result': saleResultRow})

            for result in arrayResultAuction:
                result['itemId'] = itemId

        await self.기일내역_DB_업데이트(arrayResultAuction, itemId)

        print("기일내역 완료")

    def 감정평가서_PDF_다운(self):
        print("감정평가서 다운로드")
        try:
            self.vars["window_handles"] = self.driver.window_handles
            self.driver.find_element(
                By.XPATH, "//img[@alt='감정평가서 팝업']").click()

            self.vars["win7232"] = self.wait_for_window(2000)
            self.vars["root"] = self.driver.current_window_handle
            self.driver.switch_to.window(self.vars["win7232"])

            filename = 'pdf/valuation.pdf'

            with open(filename, 'wb') as file:

                iframe = self.driver.find_element(
                    By.XPATH, "/html/frameset/frame[2]")
                self.driver.switch_to.frame(iframe)
                pdf_link = self.driver.find_element(By.TAG_NAME, "iframe")

                # write file
                with open(filename, 'wb') as handle:
                    while True:
                        try:
                            headers = {
                                # Github runner
                                "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
                                # Local
                                # "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
                            }

                            response = requests.get(
                                pdf_link.get_attribute('src'), stream=True, headers=headers)

                            if response.status_code == 200:
                                break
                        except Exception as e:
                            print(
                                "Error Write file ", e)
                            time.sleep(3)

                    if not response.ok:
                        print(response)

                    for block in response.iter_content(1024):
                        if not block:
                            break
                        handle.write(block)

                with open(filename, 'rb') as f:
                    content = f.read()

                hex = binascii.hexlify(content).decode('utf-8')

                # Delete image files
                folder = 'pdf/'
                for filename in os.listdir(folder):
                    file_path = os.path.join(folder, filename)
                    try:
                        if os.path.isfile(file_path) or os.path.islink(file_path):
                            os.unlink(file_path)
                        elif os.path.isdir(file_path):
                            shutil.rmtree(file_path)
                    except Exception as e:
                        print('Failed to delete %s. Reason: %s' %
                              (file_path, e))
        except Exception as PDF_VALUATION_Error:
            log_update.error(PDF_VALUATION_Error)

        finally:
            self.driver.close()
            self.driver.switch_to.window(self.vars["root"])
            self.driver.switch_to.frame(0)

        print("감정평가서 다운로드 완료")

        return hex

    async def crawler_data(self, itemInfo):
        log_update.debug("Start creating new item : " + itemInfo)
        formatYYYMMDDHHMM = '%Y.%m.%d %H:%M'
        formatYYYMMDD = '%Y.%m.%d'
        self.driver.get("https://www.courtauction.go.kr/")
        self.driver.set_window_size(1391, 876)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, itemInfo).click()

        itemList = []

        currentPageIndex = 1

        while True:
            itemList.clear()
            finished = False
            itemList = await self.법원경매정보_물건리스트_가져오기()

            for item in itemList:
                try:
                    # 매물 클릭
                    if (item[2] == True):
                        # 첫번째 매물
                        self.driver.find_element(
                            By.CSS_SELECTOR, ".Ltbl_list_lvl0:nth-child(1) > .txtleft a:nth-child(1)").click()
                    else:
                        # 그외 매물
                        self.driver.find_element(
                            By.NAME, item[0] + item[1]).click()

                    try:
                        # 데이터 크롤링
                        caseNumber = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[1]/td[1]").text.split(' ')[0]

                        log_update.debug("START " + caseNumber)

                        share = False

                        pdfValuation = self.감정평가서_PDF_다운()

                        log_update.debug("기본조사 시작")
                        # 기본정보
                        itemNumber = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[1]/td[2]")

                        itemType = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[1]/td[3]")

                        initialPrice = Decimal(sub(r'[^\d.]', '', self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[2]/td[1]").text))

                        minPrice = Decimal(sub(r'[^\d.]', '', self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[2]/td[2]").text))

                        bidType = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[2]/td[3]")

                        saleDate = datetime.strptime(
                            self.driver.find_element(
                                By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[3]/td").text
                            [0:16], formatYYYMMDDHHMM)

                        description = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[4]/td")

                        # 사건접수
                        caseApplyDate = datetime.strptime(self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[2]/tbody/tr[1]/td[1]")
                            .text, formatYYYMMDD)
                        # 경매개시
                        auctionApplyDate = datetime.strptime(self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[2]/tbody/tr[1]/td[2]")
                            .text, formatYYYMMDD)

                        # 배당요구종기
                        field = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[2]/tbody/tr[2]/td[1]")
                        if not field.text:
                            allocationApplyDate = None
                        else:
                            allocationApplyDate = datetime.strptime(self.driver.find_element(
                                By.XPATH, "//*[@id='contents']/div[4]/table[2]/tbody/tr[2]/td[1]").text.split("/")[-1].replace("\n", "").replace("(연기)", "").strip(), formatYYYMMDD)
                        requestPrice = Decimal(sub(r'[^\d.]', '', self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[2]/tbody/tr[2]/td[2]").text))

                        # 목록내역
                        try:
                            log_update.debug("목록내역 시작")
                            estateListTable = self.driver.find_element(
                                By.XPATH, "//*[@id='contents']/div[6]/table")

                            estateListTbody = estateListTable.find_element(
                                By.TAG_NAME, "tbody")

                            areaOfGround = 0
                            areaOfBuilding = 0
                            estateList = []

                            estateIdx = 0

                            for tr in estateListTbody.find_elements(By.TAG_NAME, "tr"):

                                tds = tr.find_elements(By.TAG_NAME, "td")

                                estateLocation = self.driver.find_element(
                                    By.XPATH,
                                    "//*[@id='contents']/div[4]/table[1]/tbody/tr[" + str(5 + estateIdx) + "]/td").text.strip()

                                estateUsage = ""

                                if estateLocation[0] == "(":
                                    for usageChar in estateLocation:
                                        if usageChar == ")":
                                            estateUsage += usageChar
                                            estateLocation = estateLocation.replace(
                                                estateUsage, "").strip()
                                            estateUsage = estateUsage.replace(
                                                "(", "").replace(")", "").strip()

                                            break
                                        else:
                                            estateUsage += usageChar
                                else:
                                    estateUsage = "기타"

                                if estateIdx == 0:
                                    itemLocation = estateLocation

                                estateList.append({
                                    "num": int(tds[0].text),
                                    "type": tds[1].text,
                                    'detail': tds[2].text,
                                    "usage": estateUsage,
                                    "location": estateLocation}, )

                                detailOfList = tds[2].text

                                if tds[1].text == "토지":
                                    thisGround = float(0)
                                    for line in detailOfList.split("\n"):
                                        if (line.startswith("주차장") or line.startswith("대") or line.startswith("임야") or line.startswith("구거") or line.startswith("잡종지") or line.startswith("묘지") or line.startswith("도로") or line.startswith("공장용지") or line.startswith("답") or line.startswith("하천") or line.startswith("전")) and line.endswith("㎡"):
                                            thisGround = float(re.findall(
                                                r'(\d+(?:\.\d+)?)', line)[0])

                                        # 지분
                                        if "매각지분" in line and "분의" in line:
                                            isShare = float(0)
                                            if len(re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)) > 0:
                                                for each in re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line):
                                                    isShare += float(each[1]) / \
                                                        float(each[0])

                                                if isShare < 1.0:
                                                    share = True
                                                    thisGround = thisGround * isShare
                                    areaOfGround += thisGround

                                elif tds[1].text == "집합건물":
                                    thisBuilding = float(0)
                                    thisGround = float(0)
                                    thisGroundArray = []
                                    groundShareIdx = 0

                                    for line in detailOfList.split("\n"):
                                        line = line.strip()
                                        # 건물
                                        if "구          조" in line and "㎡" in line:
                                            thisBuilding += float(
                                                re.findall(r'(\d+(?:\.\d+)?)', line)[0])

                                        if "면          적" in line and "㎡" in line:
                                            thisBuilding += float(
                                                re.findall(r'(\d+(?:\.\d+)?)', line)[0])

                                        # 토지
                                        # 면적
                                        if (line.startswith("학교용지") or line.startswith("주차장") or line.startswith("대") or line.startswith("임야") or line.startswith("구거") or line.startswith("잡종지") or line.startswith("묘지") or line.startswith("도로") or line.startswith("공장용지") or line.startswith("답") or line.startswith("하천") or line.startswith("전")) and (line.endswith("㎡") or line.endswith("평방미터")):
                                            thisGroundArray.append(
                                                float(re.findall(r'(\d+(?:\.\d+)?)', line)[0]))

                                        # 비율
                                        if "." in line and "분의" in line and "매각지분" not in line:
                                            line = line.replace(",", "")
                                            if len(re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)) > 0:
                                                numerator = float(re.findall(
                                                    r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)[0][0])
                                                denominator = float(re.findall(
                                                    r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line)[0][1])

                                                if len(thisGroundArray) == 0:
                                                    if thisGround == 0:
                                                        thisGround += denominator
                                                else:
                                                    thisGroundArray[groundShareIdx] = thisGroundArray[groundShareIdx] * float(
                                                        denominator / numerator)
                                                    thisGround += thisGroundArray[groundShareIdx]
                                                    groundShareIdx = groundShareIdx + 1
                                        # 지분
                                        if "매각지분" in line and "분의" in line:
                                            isShare = float(0)
                                            for each in re.findall(r'(\d+(?:\.\d+)?)\s*분의\s*(\d+(?:\.\d+)?)', line):

                                                isShare += float(each[1]) / \
                                                    float(each[0])

                                            if isShare < 1.0:
                                                share = True
                                                thisBuilding = thisBuilding * isShare
                                                thisGround = thisGround * isShare

                                    areaOfBuilding += thisBuilding
                                    areaOfGround += thisGround

                                elif tds[1].text == "건물":
                                    print("건물")

                                estateIdx = estateIdx + 1
                        except Exception as Error_목록내역:
                            log_update.error("Error_목록내역")
                            log_update.error("Error message : " + Error_목록내역)
                            log_update.error("Error line : " + line)

                        court = self.driver.find_element(
                            By.XPATH, "//*[@id='contents']/div[4]/table[1]/tbody/tr[" + str(5 + estateIdx) + "]/td").text

                        # 감정평가
                        appraisal = ""
                        try:
                            log_update.debug("감정평가 시작")
                            ulOfAppraisal = self.driver.find_element(
                                By.XPATH, "//*[@id='contents']/div[7]/table/tbody/tr/td/ul")

                            all_li = ulOfAppraisal.find_elements(
                                By.TAG_NAME, "li")

                            for li in all_li:
                                if li.text not in appraisal:
                                    appraisal += li.text + "\n"
                        except:
                            appraisal = "2008년 8월 18일 이전에 감정평가 완료된 물건에 대해서는 본 정보를 제공하지 않습니다.\n감정평가서를 참조하시기 바랍니다."

                        itemId = await self.insertItem(caseNumber,
                                                       item[0],
                                                       itemNumber.text,
                                                       itemType.text,
                                                       initialPrice,
                                                       minPrice,
                                                       bidType.text,
                                                       saleDate,
                                                       description.text,
                                                       itemLocation,
                                                       court,
                                                       caseApplyDate,
                                                       auctionApplyDate,
                                                       allocationApplyDate,
                                                       requestPrice,
                                                       appraisal,
                                                       areaOfBuilding,
                                                       areaOfGround,
                                                       0,
                                                       share,
                                                       pdfValuation)

                        log_update.debug("Complated insert: " + caseNumber)

                        await self.현황조사서_데이터(itemId, itemNumber.text)

                        # 사진
                        # 사진 이미 등록되어있는지 확인
                        try:
                            imageDuplicated = await self.checkImageDuplicated(caseNumber)
                            if imageDuplicated == True:
                                print("PASS : UPLOAD IMAGE")
                            else:
                                print("START UPLOAD IMAGE")

                                # 사진 업로드
                                checkImage = self.driver.find_element(
                                    By.XPATH, "//*[@id='contents']/div[4]/div[2]/table/tbody/tr/td")

                                if checkImage.text == "감정평가서와 현황조사서에 등록된 사진이미지가 없습니다.":
                                    print("감정평가서와 현황조사서에 등록된 사진이미지가 없습니다.")
                                else:
                                    self.vars["window_handles"] = self.driver.window_handles
                                    self.driver.find_element(
                                        By.CSS_SELECTOR, "#photo0 li:nth-child(1) img").click()
                                    self.vars["win1583"] = self.wait_for_window(
                                        2000)
                                    self.vars["root"] = self.driver.current_window_handle
                                    self.driver.switch_to.window(
                                        self.vars["win1583"])

                                    nameOfImage = self.driver.find_element(
                                        By.XPATH, "//*[@id = 'pop_contents_1']/form/div[1]/table/tbody/tr[1]/td[2]").text
                                    numOfImg = int(self.driver.find_element(
                                        By.XPATH, "//*[@id='pop_contents_1']/form/div[2]/div[2]/div/span").text)

                                    imageObjects = []
                                    imagePageIndex = 1

                                    for i in range(numOfImg):
                                        # something
                                        # Download image file
                                        print('images/' + nameOfImage +
                                              "_" + str(i) + ".png")
                                        with open('images/' + nameOfImage + "_" + str(i) + ".png", 'wb') as file:
                                            # identify image to be captured

                                            img = None
                                            while True:
                                                try:
                                                    img = self.driver.find_element(
                                                        By.XPATH, "//*[@id='pop_contents_1']/form/div[2]/table/tbody/tr[1]/td/img")
                                                    break
                                                except Exception as ImgNotFoundError:
                                                    print("ImgNotFoundError : ",
                                                          ImgNotFoundError)
                                                    time.sleep(2)

                                            # write file
                                            with open('images/' + nameOfImage + '_' + str(i) + '.png', 'wb') as handle:
                                                while True:
                                                    try:

                                                        headers = {
                                                            # Github runner
                                                            "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
                                                            # Local
                                                            # "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
                                                        }

                                                        response = requests.get(
                                                            img.get_attribute('src'), stream=True, headers=headers)

                                                        if response.status_code == 200:
                                                            break
                                                    except Exception as e:
                                                        print(
                                                            "Error Write file ", e)
                                                        time.sleep(3)

                                                if not response.ok:
                                                    print(response)

                                                for block in response.iter_content(1024):
                                                    if not block:
                                                        break
                                                    handle.write(block)

                                            uploadURL = None

                                            # Upload image to cloudFlare and get guid
                                            self.cloudFlareUpload(
                                                'images/' + nameOfImage + "_" + str(i) + ".png", imageObjects, nameOfImage)

                                        # nextpage
                                        pagination = self.driver.find_element(
                                            By.CLASS_NAME, "page2")

                                        pages = pagination.find_elements(
                                            By.TAG_NAME, 'a')
                                        for page in pages:
                                            if not page.text:
                                                if page.find_element(By.TAG_NAME,
                                                                     ("img")).get_attribute("alt") == "다음":
                                                    imagePageIndex = imagePageIndex + 1
                                                    print("GO TO PAGE : ",
                                                          imagePageIndex)
                                                    page.click()
                                                    break
                                            else:
                                                if int(page.text) == imagePageIndex+1:
                                                    imagePageIndex = imagePageIndex + 1
                                                    print("GO TO PAGE : ",
                                                          imagePageIndex)
                                                    page.click()
                                                    break

                                    await self.insertImage(imageObjects)
                                    print("사진 업로드 완료")

                                    self.driver.close()
                                    self.driver.switch_to.window(
                                        self.vars["root"])
                                    self.driver.switch_to.frame(0)
                        except Exception as Error_사진:
                            log_update.error("Error_사진")
                            log_update.error(Error_사진)

                        await self.기일내역_데이터(itemId)

                        if len(estateList) > 0:
                            for estateItem in estateList:
                                estateItem['itemId'] = itemId
                            await self.insertEstateList(estateList)

                        print("목록내역 완료")

                        # Delete image files
                        folder = 'images/'
                        for filename in os.listdir(folder):
                            file_path = os.path.join(folder, filename)
                            try:
                                if os.path.isfile(file_path) or os.path.islink(file_path):
                                    os.unlink(file_path)
                                elif os.path.isdir(file_path):
                                    shutil.rmtree(file_path)
                            except Exception as e:
                                print('Failed to delete %s. Reason: %s' %
                                      (file_path, e))

                        # 이전으로 돌아가기
                        self.driver.find_element(
                            By.XPATH, "//div[@id='contents']/div[4]/div/div/a[2]/img").click()

                    except Exception as Error_일반:
                        log_update.error("Error_일반")
                        log_update.error(Error_일반)

                        # 이전으로 돌아가기
                        self.driver.find_element(
                            By.XPATH, "//div[@id='contents']/div[4]/div/div/a[2]/img").click()

                except Exception as Error_ITEM_선택:
                    log_update.error("Error_ITEM_선택")
                    log_update.error(item)
                    log_update.error(Error_ITEM_선택)

            while True:
                try:
                    pagination = self.driver.find_element(
                        By.CLASS_NAME, "page2")
                    pages = pagination.find_elements(By.TAG_NAME, 'a')

                    for page in pages:
                        if not page.text:
                            if page.find_element(By.TAG_NAME,
                                                 ("img")).get_attribute("alt") == "다음":
                                currentPageIndex = currentPageIndex + 1
                                finished = True
                                page.click()

                                break
                        else:
                            if int(page.text) == currentPageIndex+1:
                                currentPageIndex = currentPageIndex + 1
                                finished = True
                                page.click()
                                break

                    break
                except Exception as NextPageException:
                    print("NextPageException :", NextPageException)

            # END
            if finished == False:
                break

    async def getItemsNeedUpdate(self):
        print("Get Items")
        db = Prisma()
        await db.connect()

        fromDate = datetime.now()
        fromDate = fromDate.replace(hour=0, minute=0, second=0)

        toDate = fromDate - timedelta(days=2)

        items = await db.item.find_many(
            where={
                "saleDate": {
                    "lt": fromDate,
                    "gte": toDate
                },
                "status": 0
            }
        )

        await db.disconnect()
        return items

    async def update_매각정보(self, itemId, saleDate, minSalePrice):
        db = Prisma()
        await db.connect()

        items = await db.item.update(
            where={
                'id': itemId
            },
            data={
                'saleDate': saleDate,
                'minPrice': minSalePrice
            }
        )
        await db.disconnect()

    def getCourtData(self):
        # Using readlines()
        court = {}
        file1 = open('data/court.txt', 'r', encoding='utf-8')
        Lines = file1.readlines()

        # Strips the newline character
        for line in Lines:
            court[line.split(',')[0].strip()] = line.split(',')[1].strip()

        return court

    async def parse_기일내역_table(self, source, itemId):
        formatYYYMMDD_HHMM = '%Y.%m.%d(%H:%M)'
        arrayResultAuction = []
        saleDate = ''
        minSalePrice = ''
        for tr in source:
            td = tr.find_all('td')
            if len(td) > 5:
                arrayResultAuction.append(
                    {"date": datetime.strptime(str(td[2].text).strip(), formatYYYMMDD_HHMM),
                     "type": str(td[3].text).strip(),
                     'location': str(td[4].text).strip(),
                     'minSalePrice': str(td[5].text).strip(),
                     'result': str(td[6].text).strip()})
                if str(td[3].text).strip() == "매각기일":
                    saleDate = datetime.strptime(
                        str(td[2].text).strip(), formatYYYMMDD_HHMM)
                    minSalePrice = Decimal(
                        sub(r'[^\d.]', '', str(td[5].text).strip()))

                    if "매각" in str(td[6].text).strip() and sub(r'[^\d.]', '', str(td[6].text).strip()) != '':
                        minSalePrice = Decimal(
                            sub(r'[^\d.]', '', str(td[6].text).strip()))

            else:
                arrayResultAuction.append(
                    {"date": datetime.strptime(str(td[0].text).strip(), formatYYYMMDD_HHMM),
                     "type": str(td[1].text).strip(),
                     'location': str(td[2].text).strip(),
                     'minSalePrice': str(td[3].text).strip(),
                     'result': str(td[4].text).strip()})
                if str(td[1].text).strip() == "매각기일":
                    saleDate = datetime.strptime(
                        str(td[0].text).strip(), formatYYYMMDD_HHMM)
                    minSalePrice = Decimal(
                        sub(r'[^\d.]', '', str(td[3].text).strip()))

                    if "매각" in str(td[4].text).strip() and sub(r'[^\d.]', '', str(td[4].text).strip()) != '':
                        minSalePrice = Decimal(
                            sub(r'[^\d.]', '', str(td[4].text).strip()))

        if saleDate != '':
            await self.update_매각정보(itemId, saleDate, minSalePrice)

        for result in arrayResultAuction:
            result['itemId'] = itemId

        await self.기일내역_DB_업데이트(arrayResultAuction, itemId)

    async def update_date(self):
        log_update.debug("START")
        log_update.debug("매각기일 Update 시작")
        courtData = self.getCourtData()

        # Get item need update
        items = await self.getItemsNeedUpdate()

        log_update.debug("오늘의 매각결과 업데이트 물건 수 : " + str(len(items)))

        for item in items:
            try:
                log_update.debug(item.caseNumber)
                # Open courtauctuon page
                self.setup_method("")
                url = "http://www.courtauction.go.kr/RetrieveRealEstDetailInqSaList.laf?jiwonNm=" + \
                    courtData[item.court.split('|')[0].strip(
                    )] + "&saNo=" + item.caseIndex + "&_SRCH_SRNID=PNO102014"

                # url = "http://www.courtauction.go.kr/RetrieveRealEstDetailInqSaList.laf?jiwonNm=%BC%AD%BF%EF%B5%BF%BA%CE%C1%F6%B9%E6%B9%FD%BF%F8&saNo=20210130000798&_SRCH_SRNID=PNO102014"

                self.driver.get(url)
                self.driver.implicitly_wait(time_to_wait=1000)

                html = self.driver.page_source
                soup = BeautifulSoup(html, 'html.parser')

                contents = soup.find(id='contents')
                result = None

                # 사건기본내역
                basicCaseInfo = contents.find('table', {"summary": "사건기본내역 표"})
                for tr in basicCaseInfo.find_all('tr'):
                    if "종국결과" in tr.text:
                        td = tr.find_all('td')
                        result = td[0].text
                        break
                    # result : 미종국(0[진행,유찰] or 1[낙찰:매각,매각허가결정,대금납부,대금미납]) / 취하(2) / 배당종결(3) / 기각(4) / 매각불허가(5)

                if result is not None:
                    log_update.debug("물건상태 : " + result)
                    if result == '취하':
                        # Update status of auction
                        await self.경매상태_DB_업데이트(item.id, '', 2)
                    elif result == '배당종결':
                        await self.경매상태_DB_업데이트(item.id, '', 3)
                    elif result == '기각':
                        await self.경매상태_DB_업데이트(item.id, '', 4)
                    elif result == '미종국':
                        # 물건내역 표
                        tableFlag = False
                        tables = contents.find_all(
                            'table', {"summary": "물건내역 표"})

                        for table in tables:
                            for tr in table .find_all('tr'):
                                td = tr.find_all('td')
                                if "물건번호" in tr.text:
                                    # 물건번호 확인
                                    if item.itemNumber == td[0].text:
                                        print("물건번호 : ", td[0].text)
                                        tableFlag = True
                                    else:
                                        break

                                # 매각준비 -> 매각공고 -> 매각 -> 매각허가결정 -> 대금납부 or 대금미납 or 매각불허결정
                                # status 0 진행(매각준비,매각공고,유찰) / 1 낙찰(매각,매각허가결정,대금미납) / 2 종료 (대금납부)
                                if tableFlag == True and "물건상태" in tr.text:
                                    # 매각허가결정 -> 최근입찰결과 업데이트
                                    # 유찰 -> 물건 상세조회 이동 -> 데이터 업데이트
                                    statusOfItem = td[0].text.split(
                                        '->')[-1].strip()

                                    log_update.debug("경매결과 : " + statusOfItem)

                                    if statusOfItem == "매각" or statusOfItem == "매각허가결정" or statusOfItem == "대금미납" or statusOfItem == "대금납부" or statusOfItem == "매각불허결정":

                                        if item.lastestStatus == statusOfItem:
                                            break

                                        if statusOfItem == "매각불허결정":
                                            await self.경매상태_DB_업데이트(item.id, statusOfItem, 5)
                                        else:
                                            # status -> 낙찰(1)로 변경
                                            await self.경매상태_DB_업데이트(item.id, statusOfItem, 1)

                                    elif statusOfItem == "매각준비" or statusOfItem == "매각공고" or statusOfItem == "유찰":
                                        # 상세페이지 이동해서 업데이트
                                        print(statusOfItem)

                                    else:
                                        log_update.debug("Need update 매각결과")
                                        log_update.debug(statusOfItem)
                                        log_update.debug("url : ", url)

                                    # 기일내역 업데이트
                                    self.driver.find_element(
                                        By.XPATH, "//*[@id='contents']/div[4]/div[2]/div[2]/a").click()
                                    time.sleep(1)
                                    html = self.driver.page_source
                                    soup = BeautifulSoup(html, 'html.parser')
                                    contents = soup.find(id='contents')
                                    resultOfAuctionInfo = contents.find(
                                        'table', {"summary": "기일내역 표"})
                                    resultOfAuctionTbody = resultOfAuctionInfo.find(
                                        'tbody')

                                    itemTrs = resultOfAuctionTbody.find_all(
                                        'tr')
                                    trIndx = 0

                                    while True:
                                        if itemTrs[trIndx].find('td').has_key("rowspan"):
                                            if item.itemNumber == itemTrs[trIndx].find('td').text.strip():
                                                rowSpan = int(
                                                    itemTrs[trIndx].find('td')["rowspan"])
                                                paramTrs = []
                                                for i in range(0, rowSpan):
                                                    paramTrs.append(
                                                        itemTrs[trIndx+i])
                                                await self.parse_기일내역_table(paramTrs, item.id)
                                                break

                                        trIndx = trIndx + 1

                            if tableFlag == True:
                                break
                    else:
                        log_update.debug("NEED TO UPDATE 물건상태")
                        log_update.debug("url : ", url)
                        log_update.debug("Result : ", result)

            except Exception as UpdateException:
                log_update.error(UpdateException)
                log_update.error(url)

            # close page
            self.teardown_method("")


def job():
    itemType = ["오피스텔"]

    for item in itemType:
        crawler = GetAuctionInfo()
        crawler.setup_method("")
        loop = asyncio.get_event_loop()
        loop.run_until_complete(crawler.crawler_data(item))
        crawler.teardown_method("")


def updateJob():
    crawler = GetAuctionInfo()
    crawler.setup_method("")
    loop = asyncio.get_event_loop()
    loop.run_until_complete(crawler.update_date())
    crawler.teardown_method("")


def reserve():
    updateJob()
    # job()


reserve()

# schedule.every().day.at("06:10").do(reserve)
# while True:
#     schedule.run_pending()
#     time.sleep(5)
