# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import requests
from bs4 import BeautifulSoup


class GetAuctionInfo():
    def setup_method(self, method):
        self.driver = webdriver.Chrome('./chromedriver')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def crawler_data(self):
        self.driver.get("https://www.courtauction.go.kr/")
        self.driver.set_window_size(1391, 876)
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.LINK_TEXT, "아파트").click()

        itemList = []

        # Table에서 Name 리스트 가져오기
        table = self.driver.find_elements(
            By.XPATH, "//*[@id='contents']/div[4]/form[1]/table")

        for line in table:
            chks = line.find_elements(By.NAME, "chk")
            for chk in chks:
                inputValue = chk.get_attribute("value").split(',')
                itemList.append(inputValue[1]+inputValue[2])

        for item in itemList:
            # 매물 클릭
            if (item == itemList[0]):
                # 첫번째 매물
                self.driver.find_element(
                    By.CSS_SELECTOR, ".Ltbl_list_lvl0:nth-child(1) > .txtleft a:nth-child(1)").click()

            else:
                # 그외 매물
                self.driver.find_element(By.NAME, item).click()

            time.sleep(2)

            # 데이터 크롤링

            # 이전
            self.driver.find_element(
                By.XPATH, "//div[@id='contents']/div[4]/div/div/a[2]/img").click()


crawler = GetAuctionInfo()

crawler.setup_method("")
crawler.crawler_data()
crawler.teardown_method("")
